def err(num):
    try:
        val=1/num
    except:
        print "error"
	return 

err(0)


saniya
sharma
